name: maintenance
on:
  schedule:
  - cron: "0 8 * * *"
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  maintenance:
    uses: PedroHenriques/ci_cd_workflow_templates/.github/workflows/repo_maintenance.yml@v1
    with:
      template_type: javascript_fe
      pr_reviewers: PedroHenriques
    secrets: inherit